services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend-web

networks:
  frontend-web:
    driver: bridge